api/urls.py
from django.urls import path
import drf_spectacular.views as spect
from rest_framework.urlpatterns import format_suffix_patterns
from api.views import feria_views, producto_views, horario_view

urlpatterns = [
    # API Endpoints
    path('productos/', producto_views.ProductoList().as_view()),
    path('productos/<int:pk>/', producto_views.ProductoDetail().as_view()),
    path('ferias/', feria_views.FeriaList().as_view()),
    path('ferias/<slug:pk>/', feria_views.FeriaDetail().as_view()),
    path('horarios/<slug:pk>/', horario_view.HorarioDetail().as_view()),
    # OpenAPI Endpoints:
    path(
        'doc/', spect.SpectacularAPIView.as_view(), name='schema'),
    path('doc/swagger-ui/',
         spect.SpectacularSwaggerView.as_view(
             url_name='schema'), name='swagger-ui'),
    path('doc/redoc/',
         spect.SpectacularRedocView.as_view(
             template_name='redoc.html'), name='redoc'),
    path('doc/swagger.json',
         spect.SpectacularJSONAPIView.as_view(), name='swagger-json'),
]
urlpatterns = format_suffix_patterns(urlpatterns)

ferias/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ferias, name='list-ferias'),
    path('lista/',
         views.lista_productos, name='lista-productos'),
    path('<str:feria_id>/',
         views.ferias_detail, name='feria-detail'),
    path('<str:feria_id>/<slug:slug>/', 
         views.ferias_detail, name='feria-detail'),
]

sitio/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('inicio.urls')),
    path('ferias/', include('ferias.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

ferias/models.py
''' Acá se crean los modelos base de las Ferias, junto con toda la información
    relevante de ellas '''

import datetime
import locale
from django.db import models
from django.utils.text import slugify
from ferias.utils import *

locale.setlocale(locale.LC_TIME, '')

''' Acá se crean los modelos base de las Ferias, junto con toda la información
    relevante de ellas '''


def path_producto(instance, filename):
    return 'producto/{}/{}'.format(instance.nombre_comun, filename)


def path_foto(instance, filename):
    return 'foto/{}/{}'.format(instance.feria.nombre, filename)


class Producto(models.Model):
    ''' Modelo de un producto, contiene información básica de los diferentes
        productos que se pueden encontrar en las ferias '''

    categoria = models.PositiveSmallIntegerField(
        choices=CATEGORIAS_PRODUCTOS)
    nombre_cientifico = models.CharField(max_length=128, blank=True)
    nombre_comun = models.CharField(max_length=128)
    imagen = models.ImageField(upload_to=path_producto)
    icono = models.ImageField(upload_to=path_producto)
    descripcion = models.TextField()
    temporada = models.TextField()
    precio = models.FloatField(default=0.0)

    class Meta:
        managed = True
        db_table = 'productos'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def getJson(self):
       ''' Conseguir una version json del modelo'''
       return {
           "id": self.id,
           "nombre_cientifico": self.nombre_cientifico,
           "nombre_comun": self.nombre_comun,
           "imagen": self.imagen.url,
           "icono": self.icono.url,
           "precio": self.precio
       }

    def __str__(self):
        return self.nombre_comun


class Feria(models.Model):
    ''' Modelo principal que contiene la información de las ferias del
        agricultor a nivel nacional '''

    feria_id = models.CharField(max_length=3, primary_key=True)
    codigo_url = models.CharField(max_length=30)
    nombre = models.CharField(max_length=128)
    conocida_como = models.CharField(max_length=128, blank=True)
    comite = models.CharField(max_length=128)
    administrador = models.CharField(max_length=128)
    telefono = models.CharField(max_length=15)
    provincia = models.PositiveSmallIntegerField(choices=PROVINCIAS)
    canton = models.CharField(max_length=128)
    distrito = models.CharField(max_length=128)
    direccion = models.TextField()
    latitud = models.FloatField()
    longitud = models.FloatField()
    oferta = models.ManyToManyField(Producto, blank=True)
    metodo_pago = models.CharField(max_length=128)
    estacionamiento = models.BooleanField(default=False)
    parqueo_bicicleta = models.BooleanField(default=False)
    sanitarios = models.BooleanField(default=False)
    campo_ferial = models.BooleanField(default=False)
    bajo_techo = models.BooleanField(default=False)
    agua_potable = models.BooleanField(default=False)
    accesibilidad = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'ferias'
        verbose_name = 'Feria del Agricultor'
        verbose_name_plural = 'Ferias del Agricultor'
        ordering = ['nombre']

    def get_slug(self):
        ''' Usamos esta funcion para conseguir el slug ya que
        no se permiten caracteres que no sean ASCII '''
        return slugify(self.codigo_url)

    def abre_hoy(self):
        ''' Verifica si la feria abre hoy (hora server) '''
        abre = False
        dia = datetime.datetime.now().strftime("%A")[0]
        for horario in self.horarios.all():
            if dia.lower() == horario.dia_inicio[0].lower():
                abre = True
                break
        return abre

    def __str__(self):
        return self.nombre + ", " + self.distrito


class Horario(models.Model):
    ''' Horarios de las diferentes ferias, relaciona un miembro del modelo
        Ferias con un día y hora de inicio y un día y hora final '''

    feria = models.ForeignKey(to=Feria, related_name="horarios",
                              on_delete=models.DO_NOTHING)
    dia_inicio = models.CharField(max_length=1, choices=DIAS_SEMANA)
    hora_inicio = models.TimeField()
    dia_final = models.CharField(max_length=1, choices=DIAS_SEMANA)
    hora_final = models.TimeField()

    class Meta:
        managed = True
        db_table = 'horarios'
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'

    def __str__(self):
        return (self.feria.nombre
                + " (" + self.dia_inicio + " - " + self.dia_final + ")")


class Foto(models.Model):
    ''' Fotos de las ferias. Pueden ser utilizadas como foto de portada o de
        perfil '''

    feria = models.ForeignKey(to=Feria, related_name="fotos",
                              on_delete=models.DO_NOTHING)
    descripcion = models.CharField(max_length=256)
    archivo = models.ImageField(upload_to=path_foto)
    perfil = models.BooleanField(default=False)
    portada = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'fotos'
        verbose_name = 'Foto'
        verbose_name_plural = 'Fotos'

    def __str__(self):
        return (self.descripcion + ', ' + self.feria.nombre)

ferias/forms.py
from django import forms
from ferias.models import Feria, Horario, Producto, Foto

''' Acá se crean los forms básicos para el manejo de los modelos '''


class FeriaForm(forms.ModelForm):
    feria_id = forms.CharField(
        required=True,
        help_text="Introduzca 3 caracteres que representen esta feria. Ej: "
                  " Feria de San Carlos = SCA")

    class Meta:
        model = Feria
        fields = '__all__'


class HorarioForm(forms.ModelForm):
    class Meta:
        model = Horario
        fields = '__all__'


class ProductoForm(forms.ModelForm):
    temporada = forms.CharField(
        required=False,
        help_text="Indique el rango de meses en los que este producto se "
                  "encuentra en temporada. Ej: Feb-Abr")

    class Meta:
        model = Producto
        fields = '__all__'


class FotoForm(forms.ModelForm):
    class Meta:
        model = Foto
        fields = '__all__'

api/views/feria_views.py
# ===================================================
# Clases encargadas del API relacionado a Feria
#
# Last modified: 26/01/2022 - Tyron
# ===================================================

from rest_framework import generics, filters
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema
from ferias.models import Feria
from ferias.utils import is_in_radius
from api.serializers.feria_serializer import FeriaSerializer
from api.views.utils import DynamicFieldsViewMixin
from api.docs.params.parameters import optional_params
from api.docs.params.ferias_params import ferias_params


@extend_schema(
    summary="ferias/",
    tags=['Ferias'],
    parameters=optional_params+ferias_params,)
class FeriaList(DynamicFieldsViewMixin, generics.ListAPIView):
    '''
    Get a list with all the Ferias. Some of the query parameters
    are used to filter the list. For example if we need to get
    the Ferias given the `provincia` we put in the query the
    param: `?provincia=1`
    '''
    queryset = Feria.objects.all()
    serializer_class = FeriaSerializer
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ['provincia', 'canton', 'distrito',
                        'metodo_pago', 'estacionamiento', 'parqueo_bicicleta',
                        'sanitarios', 'campo_ferial', 'bajo_techo',
                        'agua_potable', 'accesibilidad',
                        'horarios__dia_inicio', 'horarios__dia_final',
                        'horarios__hora_inicio', 'horarios__hora_final']
    search_fields = ['nombre', 'provincia',
                     'canton', 'distrito', 'horarios__dia_inicio',
                     'horarios__dia_final']

    def get_queryset(self):
        feria_id_filtered = []
        ferias = Feria.objects.all()
        # Parametros del URL
        lat = self.request.query_params.get('lat')
        lon = self.request.query_params.get('lon')
        radius = self.request.query_params.get('radius')
        # Filtrar por latitud, longitud y radio
        if lat is not None and lon is not None and radius is not None:
            index = 0
            for feria in ferias.iterator():
                # Verificar si esta en el radio
                if is_in_radius(float(lat), float(lon),
                                 feria.latitud, feria.longitud,
                                 int(radius)):
                    # Agregar ID de la feria
                    feria_id_filtered.insert(index, feria.feria_id)
                    index = index + 1
            # Filtrar las ferias que esten es el radio dado
            return ferias.filter(feria_id__in=feria_id_filtered)
        else:
            # Devolver todas las ferias si falta alguno de los parametros
            return ferias


@extend_schema(
    summary="ferias/{feria_id}/",
    tags=['Ferias'],
    parameters=optional_params)
class FeriaDetail(DynamicFieldsViewMixin, generics.RetrieveAPIView):
    ''' Get a specific Feria by their ID (pk)'''
    queryset = Feria.objects.all()
    serializer_class = FeriaSerializer

ferias/views.py
import os
import json
from django.conf import settings
from django.db.models import Q
from django.core.paginator import Paginator
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from ferias.models import Feria, Producto
from ferias.utils import is_in_radius, get_provincia_num


def openlayers(request):
    context = {'coords_cr': [-84.090725, 9.928069], 'zoom': 13, 'radio': 4000}
    return render(request, 'openlayers.html', context)

def ferias_detail(request, feria_id, slug = None):
    feria = get_object_or_404(Feria, feria_id=feria_id)
    # convertir a json para poder usarlo con facilidad con JS  
    horarios = json.loads(serializers.serialize("json", feria.horarios.all()))
    context = {
        'feria': feria,
        'horarios': json.dumps(horarios),
        'fotos': feria.fotos.all()
        }
    return render(request, 'ferias_detail.html',context)

def ferias(request):
    query = Q()
    # Input search. We use a OR operator
    query |= Q(nombre__icontains=request.GET.get('search', ''))
    query |= Q(provincia=get_provincia_num(request.GET.get('search', '')))
    query |= Q(canton__icontains=request.GET.get('search', ''))
    query |= Q(distrito__icontains=request.GET.get('search', ''))
    query |= Q(conocida_como__icontains=request.GET.get('search', ''))
    query |= Q(comite__icontains=request.GET.get('search', ''))
    query |= Q(administrador__icontains=request.GET.get('search', ''))

    # Filters. We use a AND operator
    if 'provincia' in request.GET:
        query &= Q(provincia=request.GET.get('provincia', 0))
    if 'canton' in request.GET:
        query &= Q(canton=request.GET.get('canton', ''))
    if 'distrito' in request.GET:
        query &= Q(distrito=request.GET.get('distrito', ''))
    if 'estacionamiento' in request.GET:
        query &= Q(estacionamiento=request.GET.get('estacionamiento', 1))
    if 'parqueo_bicicleta' in request.GET:
        query &= Q(parqueo_bicicleta=request.GET.get('parqueo_bicicleta', 1))
    if 'sanitarios' in request.GET:
        query &= Q(sanitarios=request.GET.get('sanitarios', 1))
    if 'bajo_techo' in request.GET:
        query &= Q(bajo_techo=request.GET.get('bajo_techo', 1))
    if 'campo_ferial' in request.GET:
        query &= Q(campo_ferial=request.GET.get('campo_ferial', 1))
    if 'agua_potable' in request.GET:
        query &= Q(agua_potable=request.GET.get('agua_potable', 1))
    if 'accesibilidad' in request.GET:
        query &= Q(accesibilidad=request.GET.get('accesibilidad', 1))

    ferias = Feria.objects.filter(query)
    # Filtrar por latitud, longitud y radio
    if 'lat' in request.GET and 'lon' in request.GET and 'radius' in request.GET:
        lat = request.GET.get('lat')
        lon = request.GET.get('lon')
        radius = request.GET.get('radius')
        index = 0
        feria_id_filtered = []
        for feria in ferias.iterator():
            # Verificar si esta en el radio
            if is_in_radius(float(lat), float(lon),
                            feria.latitud, feria.longitud,
                            int(radius)):
                # Agregar ID de la feria
                feria_id_filtered.insert(index, feria.feria_id)
                index = index + 1
        # Filtrar las ferias que esten es el radio dado          
        ferias = ferias.filter(feria_id__in=feria_id_filtered)
    # Paginación
    paginator = Paginator(ferias, 10)
    page_number = request.GET.get('page') if 'page' in request.GET else 1
    ferias_paged = paginator.get_page(page_number)

    context = {
        'ferias': ferias_paged
        }
    return render(request, 'ferias_list.html', context)

def lista_productos(request):
    query = Q()
    # Input search. We use a OR operator
    query |= Q(nombre_comun__icontains=request.GET.get('search', ''))
    productos = Producto.objects.filter(query)
    context = {
        'productos': productos,
    }
    return render(request, 'productos_list.html', context)

ferias/templates/ferias_detail.html
{% extends "base.html" %}
{% load static %}
{% load l10n %}

{% block title %}{{feria.nombre}}{% endblock title %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- ===========  Carousel =========== -->
        {% if feria.fotos.all.count > 0 %}
        <div class="col-md-12" id="carouselSection">
            <div id="carouselImgsFeria" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    {% for i in feria.fotos.all %}
                    <script>console.log('{{forloop.counter0}}');</script>
                    <button type="button" data-bs-target="#carouselImgsFeria" data-bs-slide-to="{{forloop.counter0}}"
                        class="{% if i.perfil == True %} active {% endif %}"
                        aria-current="{% if i.perfil == True %} true {% endif %}"
                        aria-label="{{i.descripcion}}"></button>
                    {% endfor %}
                </div>
                <div class="carousel-inner">
                    {% for i in feria.fotos.all %}
                    <div class="carousel-item {% if i.perfil == True %} active {% endif %}">
                        <img src="{{ MEDIA_URL }}{{i.archivo}}" alt="{{i.descripcion}}"
                            class="w-100 d-inline-block"
                            style="max-height: 40vh;object-fit: cover;"
                            loading="lazy">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselImgsFeria"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselImgsFeria"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        {% endif %}
        <!-- ===========  Info Feria =========== -->
        <div class="col-md-4" id="info-feria">
            <h1>{{feria.nombre}}</h1>
            {% if feria.abre_hoy %}
            <span class="badge bg-success">Abre hoy</span>
            {% else %}
            <span class="badge bg-danger">Cerrado hoy</span>
            {% endif %}
            <p class="text-muted">
                <i class="bi bi-geo"></i>
                {{feria.get_provincia_display}}, {{feria.canton}}, {{feria.distrito}}
            </p>
            <small><i class="bi bi-geo-alt"></i> Dirección exacta:</small>
            <p class="text-muted">
                {{feria.direccion}}
                <br>
                <a class="btn btn-info btn-sm" target="_blank"
                    href="https://www.google.com/maps/search/?api=1&query={{feria.latitud|unlocalize}},{{feria.longitud|unlocalize}}">
                    <i class="bi bi-map"></i> Ver en Google Maps
                </a>
            </p>
            <small><i class="bi bi-clock"></i> Horario:</small>
            <ul id="horarios-section">
            </ul>
        </div>
        <!-- ===========  Info Productos de la Feria =========== -->
        <div class="col-md-8" id="info-productos">
            <!-- Comodidades que ofrece la feria -->
            <div id="comodidades" class="text-centered pt-3">
                <div class="hstack gap-3">
                    <!-- Metodo pago -->
                    {% if feria.metodo_pago != '' %}                    
                    <div class="">
                        <span class="material-icons">
                            paid
                        </span><br>
                        <small>{{feria.metodo_pago}}</small>
                    </div>
                    {% endif %}
                    <!-- Estacionamiento -->
                    {% if feria.estacionamiento != 0 %}
                    <div class="">
                        <span class="material-icons">
                            local_parking
                        </span><br>
                        <small>Estacionamiento</small>
                    </div>
                    {% endif %}
                    <!-- Parqueo bici -->
                    {% if feria.parqueo_bicicleta != 0 %}
                    <div class="">
                        <span class="material-icons">
                            pedal_bike
                        </span><br>
                        <small>Parqueo Bicicleta</small>
                    </div>
                    {% endif %}
                    <!-- Sanitarios -->
                    {% if feria.sanitarios != 0 %}
                    <div class="">
                        <span class="material-icons">
                            wc
                        </span><br>
                        <small>Sanitarios</small>
                    </div>
                    {% endif %}
                    <!-- Bajo techo -->
                    {% if feria.bajo_techo != 0 %}
                    <div class="">
                        <span class="material-icons">
                            umbrella
                        </span><br>
                        <small>Bajo techo</small>
                    </div>
                    {% endif %}
                    <!-- Agua potable -->
                    {% if feria.agua_potable != 0 %}
                    <div class="">
                        <span class="material-icons">
                            local_drink
                        </span><br>
                        <small>Agua potable</small>
                    </div>
                    {% endif %}
                    <!-- Ley 7600 -->
                    {% if feria.accesibilidad != 0 %}
                    <div class="">
                        <span class="material-icons">
                            accessible
                        </span><br>
                        <small>Ley 7600</small>
                    </div>
                    {% endif %}
                </div>
                
            </div>
            {% if feria.oferta.count > 0 %}
            <h5>Productos que se venden en esta feria</h5>
            <div class="row">
            {% for producto in feria.oferta.all %}
            <!-- ===========  Info de Producto espeficico =========== -->
            <div class="col-md-3">
                <div class="card-feria" >
                    <a href="#" target="_blank">
                        <img src="{{producto.imagen.url}}" loading="lazy"
                            alt="Imagen de {{producto.nombre_comun}}"
                            class="img-fluid card-img"
                            style="width:100%;max-height: 100px;object-fit: cover;">
                    </a>
                    <div class="card-feria-container">
                        <a href="#">
                            <h6><b>{{producto.nombre_comun}}</b></h6>
                        </a>
                    </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <br>
            <div class="alert alert-info" role="alert">
                Esta feria no tiene productos asociados comuniquese con el administrador de esta página.
                <a href="#">Contacto</a>
            </div>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scriptsEnd %}
<script>
    const horarios = JSON.parse('{{horarios | safe}}');
    const horarioSection = document.getElementById('horarios-section');
    horarios.forEach(dia => {
        let horarioStr = '';
        let li = document.createElement('li');
        horarioStr += dias_dict[dia.fields.dia_inicio] + ': ';
        horarioStr += convertToAMPM(dia.fields.hora_inicio) + ' - ' + convertToAMPM(dia.fields.hora_final);
        li.innerHTML = horarioStr;
        horarioSection.appendChild(li);
    });
</script>
{% endblock %}

ferias/templates/openlayers.html
{% extends "base.html" %}
{% load static %}

{% block title %}Prueba OpenLayers{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/css/ol.css" type="text/css">
    <style>
      .map {
        height: 100vh;
        width: 100vw;
      }
    </style>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/build/ol.js"></script>
{% endblock %}

{% block content %}
    <div id="map" class="map"></div>
{% endblock %}


{% block scriptsEnd %}
<script type="text/javascript">
    var point = new ol.geom.Point(
        ol.proj.transform({{coords_cr}},'EPSG:4326', 'EPSG:3857')
    );
    var circle = new ol.geom.Circle(
        ol.proj.transform({{coords_cr}}, 'EPSG:4326', 'EPSG:3857'),
        {{radio}}
    );

    // Features
    var pointFeature = new ol.Feature(point);
    var circleFeature = new ol.Feature(circle);

    // Source
    var vectorSource = new ol.source.Vector({
        projection: 'EPSG:4326'
    });
    vectorSource.addFeatures([pointFeature, circleFeature]);

    // Vector layer
    var vectorLayer = new ol.layer.Vector({
        source: vectorSource
    });

      var map = new ol.Map({
        target: 'map',
        layers: [    
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat({{coords_cr}}),
          zoom: {{zoom}}
        })
      });

      map.addLayer(vectorLayer);
      {% comment %} http://live.osgeo.org/es/quickstart/openlayers_quickstart.html {% endcomment %}
      map.on('singleclick', function(event) {
        var coord4326 = ol.proj.transform(event.coordinate, 'EPSG:3857', 'EPSG:4326');

        console.log(coord4326);
        });
</script>
{% endblock %}

ferias/templates/productos_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Mi Lista{% endblock title %}

{% block styles %}
{% endblock %}
{% block scripts %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h4 class="text-center">Productos disponibles</h4>
            <form id="buscador" class="form-inline" method="get" action="./" accept-charset="utf-8" enctype="multipart/form-data">
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" id="search" aria-describedby="searchHelp"
                            placeholder="Buscar por nombre" name="search">
                        <button type="submit" class="btn btn-primary" value="submit" onclick="normalSearch();"><i class="bi bi-search"></i> Buscar</button>
                    </div>
                </div>
            </form>
            <div class="list-group shadow-sm mb-5 bg-body rounded">
            {% for producto in productos %}
                <label class="list-group-item d-flex justify-content-start align-items-center" onclick='setProduct("{ \"producto\": {{producto.getJson}}, \"quantity\": 1 }")' style="cursor: pointer;">
                    <img src="{{ MEDIA_URL }}{{ producto.imagen }}" class="img-circle me-2" width="40"/>
                    <div class="flex-grow-1">
                        <b>{{ producto.nombre_comun }}</b><br>
                        <figcaption class="figure-caption">{{ producto.nombre_cientifico }}</figcaption>                        
                    </div>
                    <b>₡ {{producto.precio}}&nbsp;&nbsp;</b>
                    <button type="button" class="btn btn-info">+</button>
                </label>
            {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            
            <h4 class="text-center">Mi lista - Posible total: <span id="total"></span></h4>
            <button type="button" class="btn btn-primary" onclick="copyToClipboard(this)">Copiar lista</button>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteModal">Borrar lista</button>
            <div class="list-group shadow-sm mb-5 bg-body rounded" id="list-products">
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Info</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
               ¿Desea borrar la lista?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="deleteList()" data-bs-dismiss="modal">Borrar lista</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
            </div>
            </div>
        </div>
        </div>
</div>
{% endblock %}
{% block scriptsEnd %}
<script src="{% static 'js/lista_productos.js' %}" type="text/javascript"></script>
{% endblock %}